<%@ Page Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="frmUpdateOffers.aspx.cs" Inherits="Admin_frmUpdateOffers" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<center>
<br />
<h3>
<b style="color:Green">UPDATE THE OFFERS</b>
</h3>
<br />
<fieldset style="width: 200px">
<asp:GridView ID="GdvUpdateOffers" runat="server" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" 
        BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Vertical" 
        onrowdeleting="GdvUpdateOffers_RowDeleting" 
        onrowediting="GdvUpdateOffers_RowEditing">
    <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
    <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
    <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
    <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
    <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
    <AlternatingRowStyle BackColor="#DCDCDC" />
    </asp:GridView>
</fieldset>
<br />
<br />
<br />
<fieldset id="FldstUpdate" visible="false" runat="server" style="width: 300px"><legend style="color:Green"> *Update The Offers </legend>
<table>
<tr>
<td align="right"><b style="color:Blue"> TalkTime :</b></td>
<td align="left"><asp:TextBox ID="TxtTalktime" runat="server"></asp:TextBox>
<asp:RequiredFieldValidator ID="RfvTalktime" ControlToValidate="TxtTalktime" Text="*" runat="server"></asp:RequiredFieldValidator>
</td>
</tr>
<tr>
<td align="right"><b style="color:Blue"> Validity :</b></td>
<td align="left"><asp:TextBox ID="TxtValidity" runat="server"></asp:TextBox>
<asp:RequiredFieldValidator ID="RfvValidity" ControlToValidate="TxtValidity" Text="*" runat="server"></asp:RequiredFieldValidator>
</td>
</tr>
<tr>
<td align="right"><b style="color:Blue"> Status :</b></td>
<td align="left"><asp:RadioButtonList ID="RbtnStatus" runat="server" 
        RepeatDirection="Horizontal">
    <asp:ListItem>Buy Now</asp:ListItem>
    <asp:ListItem>Out Of Stock</asp:ListItem>
    </asp:RadioButtonList>
</td>
</tr>
</table>
<br />
<asp:Button ID="BtnUpdate" Text="UPDATE" runat="server" onclick="BtnUpdate_Click" />
<br />
<br />
</fieldset>
<br />
<asp:Label ID="LblMsg" Visible="false" runat="server"></asp:Label>
<br />
<br />
</center>
</asp:Content>

